---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 713395890673856512-9kvEny4FpyyllHhHNUNvvbIVqVPZLXJ
:access_token_secret: s5LKxnzcChpteYOyl1wPRAKKWp4cDnigNEHJF6QuIaHjs
